/**
 * Persistence of a scored attempt onto a session (features 105/106/107;
 * extracted from server.ts by feature 117 so the write path is unit-testable
 * without an HTTP port).
 *
 * Contracts:
 *   AttemptStorage     — minimal persistence surface (implemented by
 *                        `createStorage()` in storage.ts, following the same
 *                        pattern as SessionStartDeps / ContextStorage).
 *   PersistAttemptParams — evaluation + persistence coordinates.
 *   persistAttempt(storage, params) : void — never throws; a legacy v1 file
 *                        or a disk error is swallowed after the in-memory
 *                        mutation so the caller's HTTP response is unaffected.
 *
 * Semantics (unchanged from its server.ts original):
 *   - No sessionId → no-op (the attempt was never asked to persist).
 *   - Attempts always target the LAST question (continuous sessions grow
 *     `questions[]`, feature 107) and append to the named fragment, or to the
 *     full answer when `full` is set.
 *   - After the write the profile is re-aggregated from all sessions
 *     (updateProfile) and the session's topicPrompt is pushed onto
 *     `recentTopics` (deduped, capped at 12). The LLM-generated question is
 *     deliberately NOT stored there: it may be derived from an attached
 *     document and would leak into future sessions (see persistAttempt).
 */

import { updateProfile } from "../practice/learner.ts";
import type { Evaluation } from "../practice/practice.ts";
import type { AttemptWord, Profile, SessionV2 } from "./storage.ts";

/** Minimal persistence surface `persistAttempt` needs (implemented by storage.ts). */
export interface AttemptStorage {
  loadSession(id: string): SessionV2 | undefined;
  saveSession(session: SessionV2): void;
  loadProfile(): Profile;
  saveProfile(profile: Profile): void;
  loadAllSessions(): SessionV2[];
}

export interface PersistAttemptParams {
  evaluation: Evaluation;
  sessionId?: string;
  fragmentId?: string;
  userText: string;
  target: string;
  /** Colored word-level alignment (feature 106); empty for text-only attempts. */
  words?: AttemptWord[];
  /** Fragment score override (feature 106: align score, coherent with words). */
  score?: number;
  /** Persist as the question's full answer instead of a fragment (feature 105). */
  full?: boolean;
  /** Pass decision (feature 105: score >= passThreshold); overrides evaluation.next. */
  passed?: boolean;
}

/**
 * Append the attempt to a session and re-aggregate the learner profile.
 *
 * @param storage - session/profile persistence surface
 * @param params - evaluation plus where to persist (sessionId/fragmentId)
 */
export function persistAttempt(storage: AttemptStorage, params: PersistAttemptParams): void {
  const { evaluation, sessionId, fragmentId, userText, words = [], score, full = false, passed } = params;
  if (!sessionId) return;
  const session = storage.loadSession(sessionId);
  if (!session) return;
  // Continuous sessions (feature 107) grow `questions[]`; attempts always
  // target the LAST question, never questions[0].
  const question = session.questions.at(-1);
  if (!question) return;
  const passedFlag = passed ?? evaluation.next;
  if (full) {
    question.fullAttempt = {
      text: userText,
      words,
      score: score ?? evaluation.score,
      startedAt: new Date().toISOString(),
      durationMs: 0,
    };
    question.eval = {
      score: evaluation.score,
      verdict: evaluation.verdict,
      matched: evaluation.matched,
      missing: evaluation.missing,
      extra: evaluation.extra,
      issues: evaluation.issues,
      tips: evaluation.tips,
      next: passedFlag,
    };
  } else {
    if (!fragmentId) return;
    const frag = question.fragments.find((f) => f.id === fragmentId);
    if (!frag) return;
    // Fragments created by session-start may lack the attempts array; initialize
    // it defensively so the first attempt never crashes.
    frag.attempts = frag.attempts ?? [];
    frag.attempts.push({
      text: userText,
      words,
      score: score ?? evaluation.score,
      startedAt: new Date().toISOString(),
      durationMs: 0,
    });
    if (passedFlag) frag.passed = true;
  }
  // refresh profile from aggregated data
  const profile = storage.loadProfile();
  const sessions = storage.loadAllSessions();
  updateProfile(profile, sessions);
  // `recentTopics` feeds the LEARNER MEMORY block of every future session, so
  // it must hold the USER's role instruction (session config) only. Never
  // `question.q`: that text was generated by the LLM reading the DOCUMENT
  // CONTEXT of an attached file (feature 104) and would leak document-specific
  // content (e.g. a CV detail) into sessions created without that document.
  const topic = session.config.topicPrompt.trim();
  if (topic) {
    profile.recentTopics = [topic, ...(profile.recentTopics ?? []).filter((t) => t !== topic)].slice(0, 12);
  }
  storage.saveProfile(profile);
  try {
    storage.saveSession(session);
  } catch {
    // v1 session file: compatibility view — never rewrite it (feature 102)
  }
}
